version: '3'

services:
  mariadb:
    image: mariadb:10
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
    ports:
      - 3306:3306

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      DB_VENDOR: MARIADB
      DB_URL: mariadb
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      USER_UPDATE_EVENT_NOTIFICATION_URL: "http://host.docker.internal:3000/patch-user"
      DEBUG: true
      DEBUG_PORT: "*:8787"
    entrypoint: /opt/keycloak/bin/kc.sh --debug start-dev --import-realm --features=declarative-user-profile
    ports:
      - 8080:8080
      - 8787:8787
    volumes:
      - ./target/rezoleo-providers-1.0-SNAPSHOT.jar:/opt/keycloak/providers/rezoleo-providers-1.0-SNAPSHOT.jar
      - ./rezoleo-realm-export.json:/opt/keycloak/data/import/rezoleo-realm-export.json
    depends_on:
      - mariadb
    extra_hosts:
      - "host.docker.internal:host-gateway"
