name: Test
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build with Maven
        run: mvn install

      - name: Start containers
        run: docker-compose up -d

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: test/package-lock.json

      - name: Install dependencies
        working-directory: ./test
        run: npm ci
      - name: Install Playwright Browsers
        working-directory: ./test
        run: npx playwright install --with-deps

      - name: Run tests
        working-directory: ./test
        run: npm run test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: test/playwright-report/
          retention-days: 30

      - name: Stop containers
        if: always()
        run: docker-compose down
